#!/usr/bin/env python3
"""Auxlo CLI - One command to rule them all.

Usage:
    auxlo add "task description"
    auxlo run
    auxlo config              # Show current config
    auxlo config --model <model>
    auxlo config --base-url <url>
    auxlo config --api-key <key>
    auxlo status
    auxlo logs
"""
import os
import re
import sys
import json
import subprocess
from pathlib import Path

# Find actual auxlo directory (resolve symlinks)
_AUXLO_SCRIPT = Path(__file__).resolve()
AUXLO_DIR = _AUXLO_SCRIPT.parent
TASKS_DIR = AUXLO_DIR / "tasks"
CONFIG_FILE = AUXLO_DIR / ".auxlo_config.json"
ENV_FILE = AUXLO_DIR / ".env"

def load_config():
    """Load or create config."""
    if CONFIG_FILE.exists():
        return json.loads(CONFIG_FILE.read_text())
    return {
        "model": "stepfun-ai/step-3.5-flash",
        "base_url": "https://integrate.api.nvidia.com/v1",
        "api_key": os.environ.get("NVIDIA_API_KEY", "")
    }

def save_config(config):
    """Save config to both JSON and .env file."""
    CONFIG_FILE.write_text(json.dumps(config, indent=2))
    # Also save to .env for shell scripts
    env_content = f"""# Auxlo Configuration
# Generated by auxlo config command
NVIDIA_API_KEY={config.get('api_key', '')}
NVIDIA_BASE_URL={config.get('base_url', 'https://integrate.api.nvidia.com/v1')}
AUXLO_MODEL={config.get('model', 'stepfun-ai/step-3.5-flash')}
"""
    ENV_FILE.write_text(env_content)

def cmd_add(task: str):
    """Add a new task."""
    TASKS_DIR.mkdir(exist_ok=True)
    
    # Generate filename from task
    name = re.sub(r"[^a-z0-9]", "_", task.lower())[:40]
    timestamp = len(list(TASKS_DIR.glob("*.md")))
    filename = TASKS_DIR / f"task_{timestamp:03d}_{name}.md"
    
    filename.write_text(f"# Task\n\n{task}\n")
    print(f"Added: {filename.name}")
    return filename

def cmd_run():
    """Run the evolution loop."""
    print("Starting Auxlo evolution...")
    result = subprocess.run(
        ["bash", str(AUXLO_DIR / "scripts" / "evolve.sh")],
        cwd=AUXLO_DIR,
        env={**os.environ, "AUXLO_RUNNING": "1"}
    )
    return result.returncode

def cmd_config(args):
    """Change or show configuration."""
    config = load_config()
    
    # If no args, show current config
    if not any([args.model, args.base_url, args.api_key, args.list_models]):
        print("Current Configuration:")
        print(f"  Model:     {config.get('model', 'not set')}")
        print(f"  Base URL:  {config.get('base_url', 'not set')}")
        print(f"  API Key:   {'***' + config.get('api_key', '')[-8:] if config.get('api_key') else 'not set'}")
        print()
        print("To change:")
        print("  auxlo config --model <model>")
        print("  auxlo config --base-url <url>")
        print("  auxlo config --api-key <key>")
        print()
        print("Preset models:")
        print("  - stepfun-ai/step-3.5-flash (NVIDIA, default)")
        print("  - anthropic/claude-3-5-sonnet-20241022")
        print("  - openai/gpt-4o")
        print("  - google/gemini-2.0-flash")
        return 0
    
    if args.list_models:
        print("Available models:")
        print("  NVIDIA:")
        print("    - stepfun-ai/step-3.5-flash")
        print("    - meta/llama-3.1-nemotron-70b-instruct")
        print("  Anthropic:")
        print("    - claude-3-5-sonnet-20241022")
        print("    - claude-3-5-haiku-20241022")
        print("  OpenAI:")
        print("    - gpt-4o")
        print("    - gpt-4o-mini")
        print("  Google:")
        print("    - gemini-2.0-flash")
        print("    - gemini-1.5-pro")
        return 0
    
    changed = False
    if args.model:
        config["model"] = args.model
        print(f"Model: {args.model}")
        changed = True
    
    if args.base_url:
        config["base_url"] = args.base_url
        print(f"Base URL: {args.base_url}")
        changed = True
    
    if args.api_key:
        config["api_key"] = args.api_key
        print(f"API Key: {'***' + args.api_key[-8:]}")
        changed = True
    
    if changed:
        save_config(config)
        print("Configuration saved!")
    
    return 0

def cmd_status():
    """Show status."""
    config = load_config()
    print(f"Model:     {config.get('model', 'not set')}")
    print(f"Base URL:  {config.get('base_url', 'not set')}")
    api_key = config.get('api_key', '')
    print(f"API Key:   {'***' + api_key[-8:] if api_key else 'not set'}")
    print()
    
    tasks = list(TASKS_DIR.glob("*.md"))
    print(f"Tasks: {len(tasks)}")
    for t in sorted(tasks)[:5]:
        print(f"  - {t.name}")
    if len(tasks) > 5:
        print(f"  ... and {len(tasks) - 5} more")
    print()
    
    results_file = AUXLO_DIR / "results.tsv"
    if results_file.exists():
        lines = results_file.read_text().strip().split("\n")
        if len(lines) > 1:
            last = lines[-1].split("\t")
            print(f"Last run: {last[2]} passed, score: {last[1]}")
    else:
        print("No runs yet. Run `auxlo run` first.")

def cmd_logs(lines: int = 20):
    """Show recent logs."""
    log_file = AUXLO_DIR / "evolve.log"
    if log_file.exists():
        content = log_file.read_text().split("\n")
        print("\n".join(content[-lines:]))
    else:
        print("No logs yet. Run `auxlo run` first.")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)
    
    cmd = sys.argv[1]
    
    if cmd == "add":
        if len(sys.argv) < 3:
            print("Usage: auxlo add \"task description\"")
            sys.exit(1)
        sys.exit(0 if cmd_add(sys.argv[2]) else 1)
    
    elif cmd == "run":
        sys.exit(cmd_run())
    
    elif cmd == "config":
        import argparse
        parser = argparse.ArgumentParser(description="Configure Auxlo")
        parser.add_argument("--model")
        parser.add_argument("--base-url")
        parser.add_argument("--api-key")
        parser.add_argument("--list-models", action="store_true", help="Show available models")
        args = parser.parse_args(sys.argv[2:] if len(sys.argv) > 2 else [])
        sys.exit(cmd_config(args))
    
    elif cmd == "status":
        cmd_status()
        sys.exit(0)
    
    elif cmd == "logs":
        lines = int(sys.argv[2]) if len(sys.argv) > 2 else 20
        cmd_logs(lines)
        sys.exit(0)
    
    else:
        print(f"Unknown command: {cmd}")
        print(__doc__)
        sys.exit(1)
